### ISSUE TITLE
Trigger Zenodo uploading via GHA when PR is merged

### ISSUE THREAD

**Issue by mrakitin** [nsls2-conda-envs/testenv#3]
https://stackoverflow.com/a/61565445/4143531

```yaml
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
```
